### ISSUE TITLE
Cron library throwing errors

### ISSUE THREAD

**Issue by jwindmuller** [rpmsoftware/coast-guard#14]
Today I had to manually run coast guard because the cron library was producing errors:

```
Mar 09 07:20:35 coast-guard app/clock.1: /app/node_modules/cron/lib/cron.js:243 
Mar 09 07:20:35 coast-guard app/clock.1: 					throw new Error( 
Mar 09 07:20:35 coast-guard app/clock.1: 					^ 
Mar 09 07:20:35 coast-guard app/clock.1: Error: Something went wrong. cron reached maximum iterations. 
Mar 09 07:20:35 coast-guard app/clock.1: Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string 
Mar 09 07:20:35 coast-guard app/clock.1: Time Zone: "" - Cron String: 0 0 8 * * * - UTC offset: -07:00 - current Date: Sat Mar 09 2019 15:20:34 GMT+0000 
Mar 09 07:20:35 coast-guard app/clock.1:     at CronTime._getNextDateFrom (/app/node_modules/cron/lib/cron.js:243:12) 
Mar 09 07:20:35 coast-guard app/clock.1:     at CronTime.sendAt (/app/node_modules/cron/lib/cron.js:151:17) 
Mar 09 07:20:35 coast-guard app/clock.1:     at CronTime.getTimeout (/app/node_modules/cron/lib/cron.js:170:29) 
Mar 09 07:20:35 coast-guard app/clock.1:     at CronJob.start (/app/node_modules/cron/lib/cron.js:561:31) 
Mar 09 07:20:35 coast-guard app/clock.1:     at new CronJob (/app/node_modules/cron/lib/cron.js:524:10) 
Mar 09 07:20:35 coast-guard app/clock.1:     at Object.<anonymous> (/app/index.js:13:5) 
Mar 09 07:20:35 coast-guard app/clock.1:     at Module._compile (module.js:652:30) 
Mar 09 07:20:35 coast-guard app/clock.1:     at Object.Module._extensions..js (module.js:663:10) 
Mar 09 07:20:35 coast-guard app/clock.1:     at Module.load (module.js:565:32) 
Mar 09 07:20:35 coast-guard app/clock.1:     at tryModuleLoad (module.js:505:12)  
Mar 09 07:20:35 coast-guard app/clock.1:     at Function.Module._load (module.js:497:3) 
Mar 09 07:20:35 coast-guard app/clock.1:     at Function.Module.runMain (module.js:693:10) 
Mar 09 07:20:35 coast-guard app/clock.1:     at startup (bootstrap_node.js:188:16) 
Mar 09 07:20:35 coast-guard app/clock.1:     at bootstrap_node.js:609:3 
Mar 09 07:20:35 coast-guard heroku/clock.1: Process exited with status 1 
```

**Comment by rpmjade** [comment]
Daylight savings?

**Comment by demyansda** [comment]
Heroku deployed, date/time aware applications need TZ environment variable to be set. For example, TZ=Canada/Mounain.
Also people facing that error usually fix it upgrading cron library.

**Comment by jwindmuller** [comment]
Removed the scheduling from the code and moved into a heroku addon that lets us run code at certain times during the day.
